Repository fusionjs/fusion-plugin-node-performance-emitter, pull requests merged in 2018-09, with the labels that each got.

#138 Switch to gc-stats module
  docs/migrations/00138.md
  package.json
  src/__tests__/index.node.js
  src/server.js
  yarn.lock
Labels: breaking, dependencies, performance

#139 Release v1.0.5
  package.json
Labels: release

#140 Add sideEffects:false field to package.json
  package.json
Labels: bugfix

#142 Release v1.0.6
  package.json
Labels: release
